In [22]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
def sigmoid_derivative(x):
    return x * (1 - x)

In [23]:
import numpy as np
X = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
y = np.array([[0, 1, 1, 0]]).T

In [24]:
syn0 = 2 * np.random.random((3, 4)) - 1  # [-1.0,  1.0)
syn1 = 2 * np.random.random((4, 1)) - 1

In [25]:
for j in range(1):
    l1 = sigmoid(np.dot(X, syn0))
    l2 = sigmoid(np.dot(l1, syn1))
    l2_delta = (y - l2)*sigmoid_derivative(l2)
    l1_delta = l2_delta.dot(syn1.T) * sigmoid_derivative(l1)
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)

In [26]:
array = np.ones([10, 10])

In [27]:
a = np.random.binomial([array], 0.2)

4

In [66]:
import numpy as np
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
alpha,hidden_dim,dropout_percent,do_dropout = (0.5,4,0.2,True)
synapse_0 = 2*np.random.random((3,hidden_dim)) - 1
synapse_1 = 2*np.random.random((hidden_dim,1)) - 1
for j in range(1):
    layer_1 = (1/(1+np.exp(-(np.dot(X,synapse_0)))))
    print(layer_1)
    if(do_dropout):
        drop_out = np.random.binomial([np.ones((len(X),hidden_dim))],1-dropout_percent)[0]
        print(drop_out)
        print(drop_out.mean())
        layer_1 *= drop_out
        print(layer_1)
    layer_2 = 1/(1+np.exp(-(np.dot(layer_1,synapse_1))))
    layer_2_delta = (layer_2 - y)*(layer_2*(1-layer_2))
    if j % 5000 == 0:
        print(np.mean((layer_2 - y) ** 2))
    layer_1_delta = layer_2_delta.dot(synapse_1.T) * (layer_1 * (1-layer_1))
    synapse_1 -= (alpha * layer_1.T.dot(layer_2_delta))
    synapse_0 -= (alpha * X.T.dot(layer_1_delta))

[[0.52562506 0.67949173 0.43497207 0.45491656]
 [0.71988324 0.6364634  0.54772664 0.24208895]
 [0.39467491 0.49178841 0.35930219 0.56496563]
 [0.60194817 0.44417389 0.46871313 0.33201267]]
[[1 1 1 1]
 [1 0 1 1]
 [1 0 1 0]
 [1 1 1 0]]
0.75
[[0.52562506 0.67949173 0.43497207 0.45491656]
 [0.71988324 0.         0.54772664 0.24208895]
 [0.39467491 0.         0.35930219 0.        ]
 [0.60194817 0.44417389 0.46871313 0.        ]]
0.21988738082253068
